# Generated by Django 4.2.6 on 2023-10-22 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userresume_user_resume_userextracteddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextracteddata',
            old_name='User',
            new_name='user',
        ),
    ]
