# Generated by Django 4.2.6 on 2023-10-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_rename_user_userextracteddata_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tc',
        ),
    ]
