# Generated by Django 4.2.6 on 2023-10-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_remove_user_tc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresume',
            name='user_resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
