# Generated by Django 4.2.6 on 2024-02-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_remove_user_name_user_fname_user_lname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userresume',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExtractedData',
        ),
        migrations.DeleteModel(
            name='UserResume',
        ),
    ]
